metadata:
  name: web-wiki
  short_name: web-wiki
  description: 'A library of react, webdesign and css solutions to common questions.'
  language: en
  url: 'http://localhost'
  pathPrefix: /
  gaTrackingId: null
  favicon: /assets/favicon.png
  themeColor: '#0066cc'
header:
  enabled: true
  logo: /assets/logo.png
  helpUrl: "https://boogi.netlify.app/configuration/setting-up"
  links: []
sidebar:
  ignoreIndex: false
  forcedNavOrder: []
  expanded: []
  groups: 
    - order: 1
      path: "/gettingstarted"
      title: ":rocket: Getting Started"
    - order: 2
      path: "/css"
      title: ":sparkles: CSS"
    - order: 3
      path: "/react"
      title: ":rocket: React"
    - order: 4
      path: "/strivecloud"
      title: ":cloud: strivecloud"
  links: 
    - text: BooGi
      link: https://github.com/filipowm/boogi
  poweredBy: {}
  enabled: true
pwa:
  enabled: true
  manifest:
    icon: /assets/logo.png
    display: minimal-ui
    crossOrigin: anonymous
features:
  editOnRepo:
    editable: true
    location: 'http://localhost'
    type: github
  search:
    enabled: true
    indexName: docs
    showStats: true
    startComponent: input
    placeholder: Search...
    pagination:
      enabled: true
  rss:
    enabled: false
    showIcon: true
    copyright: ''
    categories: []
    matchRegex: ^/
    outputPath: /rss.xml
  darkMode:
    enabled: true
    default: false
search:
  enabled: true
  startComponent: input
  placeholder: Search...
  pagination:
    enabled: false
