# This is default jargon that you can use. Feel free to change it. See: https://boogi.netlify.app/editing/rich_content/abbreviations
'web-wiki':
  name: web-wiki
  long_name: web-wiki
  description: A library of react, webdesign and css solutions to common questions.
